const blogsTableBody = document.createElement('blogsTableBody');
const buttonShowForm = document.createElement('buttonShowForm');
const postsContainer = document.createElement('postsContainer');
const formContainer = document.createElement('formContainer');
const formTitle = document.createElement('formTitle');
const textIdPost = document.createElement('textIdPost');
const textTitle = document.createElement('textTitle');
const textSubTitle = document.createElement('textSubTitle');
const textDescription = document.createElement('textDescription');
const textUrlImage = document.createElement('textUrlImage');
const buttonSave = document.createElement('buttonSave');
const myModal = document.getElementById('myModal'); //cambiar
const showModal = document.getElementById('showModal');